apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: estresse-cpu-negocio
  namespace: default
spec:
  mode: all
  selector:
    labelSelectors:
      app: negocio-api
  stressors:
    cpu:
      workers: 6
      load: 100
  duration: "60s"